### ISSUE TITLE
Setting the session-timeout in web.xml has no effect

### ISSUE THREAD

**Issue by Macoshark** [jeetmp3/spring-session#13]
I've had the following lines in my web.xml for a long time:

```
<session-config>
    <session-timeout>525600</session-timeout> 
    <cookie-config>
        <max-age>31536000</max-age>
    </cookie-config>
</session-config>
```

After taking spring-session into use I get the standard 30 minute sessions and not the longer sessions defined in web.xml. 

I can extend the redis key expiration time by putting the following line in Config.groovy

```
springsession.maxInactiveInterval = 525600
```

But that still doesn't set the expiration date on the session cookie.

**Comment by jeetmp3** [comment]
Hi @Macoshark sorry for the late response. Session cookie suppose to be expired at the time on session expiration.  Configuring property `springsession.maxInactiveInterval` will extend the session duration.

**Comment by AhamedSKR** [comment]
The session cookie is removed whenever the browser window is closed. The default max age property is  not working. How to set cookie max age?

**Comment by jeetmp3** [comment]
@AhamedSKR I guess you're mixing session cookie with the Persistent cookie (e.g. remember me cookie). Session cookie intended to expire whenever session closed or browser closed. SESSION cookie in this plugin is HttpSession cookie. So the maxInactiveInterval (which is now `maxInactiveIntervalInSeconds`) set the cookie expire time in seconds which means if you don't close the browser then after the specified time interval session cookie will be expired and your session will be closed. Check this [Session vs Persistence cookie](http://www.cisco.com/c/en/us/support/docs/security/web-security-appliance/117925-technote-csc-00.html). Hope this answers your query.
