### ISSUE TITLE
Code for 1.2.2-RC1?

### ISSUE THREAD

**Issue by erichelgeson** [jeetmp3/spring-session#16]
I've been playing with alternative stores with `1.2.2-RC1` and would love to help out with the JDBC stuff. I've used spring-session in grails 3 quite a bit but have a legacy grails 2 app this would be useful for as well. I don't see the code for the published RC in this repo.

Thanks!

**Comment by jeetmp3** [comment]
@erichelgeson code for JDBC stuff is in branch [1.2.2](https://github.com/jeetmp3/spring-session/tree/1.2.2). You can go through the code and share your thoughts.

**Comment by erichelgeson** [comment]
Thanks!
