### ISSUE TITLE
Support Redis Sentinel

### ISSUE THREAD

**Issue by ctoestreich** [jeetmp3/spring-session#2]
You should avoid setting your own connection properties to redis and simply use the redis plugin to manage your connection.  This way getting support for sentinel and property file support for sentinel will be inherited.

**Comment by jeetmp3** [comment]
@ctoestreich spring-session uses spring-data-redis project to connect with Redis instance. Adding redis plugin to manage redis connection won't help that much. Spring-data-redis provides sentinel support itself.
