### ISSUE TITLE
Ability to enable-disable spring-session plugin from config file?

### ISSUE THREAD

**Issue by adityathakur-rxlogix** [jeetmp3/spring-session#27]
It would be awesome if we can have a config driven enable-disable property in the plugin itself.
Following code added SpringSessionGrailsPlugin achieves that. 

`
def doWithSpring = {

        mergeConfig(application)
        ConfigObject conf = application.config.springsession

        if(conf.enabled == false) {
            println "\n++++++ Skipped configuring Spring session"
            println "\nSpring session is disabled from config"
            return
        }
        ....
`

**Comment by jeetmp3** [comment]
Closed via #30
