### ISSUE TITLE
Cookie name and dbIndex not working

### ISSUE THREAD

**Issue by darinmanica** [jeetmp3/spring-session#4]
I've added the following values to my Config.groovy:

```
springsession.strategy.defaultStrategy.cookie.name="MY_COOKIE"
springsession.redis.connectionFactory.dbIndex=2
```

Spring session is working and I'm seeing the sessions in redis; however, they appear in the 0 database (rather than 2) and the cookie is named `SESSION` rather than `MY_COOKIE`.  It appears that my configuration isn't being used.  Other settings, such as the redis password, are working fine.  Only these 2 values are being ignored.

**Comment by jeetmp3** [comment]
Hi @darinmanica thanks for pointing the issue. Same has been fixed. you can upgrade the new version 1.1
Note: Property springsession.strategy.defaultStrategy.cookie.name is now changed to springsession.strategy.cookie.name
Let us know if you face the same issue again

**Comment by darinmanica** [comment]
The 1.1 build works great and fixes the issue.  Thank you!
